"""plan add autoincrement

Revision ID: 963c30733c53
Revises: bbcca0a98431
Create Date: 2025-03-18 13:07:50.559747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963c30733c53'
down_revision: Union[str, None] = 'bbcca0a98431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credits_id', table_name='credits')
    op.drop_index('ix_dictionary_id', table_name='dictionary')
    op.drop_index('ix_payments_id', table_name='payments')
    op.drop_index('ix_plans_id', table_name='plans')
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_plans_id', 'plans', ['id'], unique=False)
    op.create_index('ix_payments_id', 'payments', ['id'], unique=False)
    op.create_index('ix_dictionary_id', 'dictionary', ['id'], unique=False)
    op.create_index('ix_credits_id', 'credits', ['id'], unique=False)
    # ### end Alembic commands ###
