"""change

Revision ID: a02fc1710917
Revises: 1c6421139bb6
Create Date: 2025-03-17 21:22:02.133323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a02fc1710917'
down_revision: Union[str, None] = '1c6421139bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login',
               existing_type=mysql.VARCHAR(length=22),
               type_=sa.String(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=22),
               existing_nullable=True)
    # ### end Alembic commands ###
